#!/usr/bin/expect

set name_source [lindex $argv 0]
set name_destination [lindex $argv 1]
set log [open "logs.log" w]

# transparent ssh to BSE Node and next to globus client 
spawn ssh root@202.29.226.170 ssh quser@10.10.1.15

send "myproxy-logon -s elephant.globus.org\r"
expect "phrase:"
send "vk0kipN;ik\r"
expect { 
	"" { puts $log $expect_out(buffer) }
}
send "globus-url-copy -vb $name_source $name_destination \r"
expect {
    "inst" { puts $log $expect_out(buffer) ; exp_continue }
}